spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://floread.cn3uwjb0drm1.ap-northeast-2.rds.amazonaws.com:3306/floread_db
    username: root
    password: 1601a0389